name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    
    - uses: actions/checkout@v1
    - name: Build the Docker image
      if: ${{ github.event_name == 'pull_request' }}
      shell: powershell
      run: |
        $version = $(Get-Date -Format yyyyMMddHHmmss)
        docker build . --file Dockerfile --tag webapplication-aspnet:$version

    - name: Push the Docker image
      if: ${{ github.event_name == 'push' }}
      shell: powershell
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        docker login --username ${Env:DOCKER_USERNAME} --password ${Env:DOCKER_PASSWORD}
        $ErrorActionPreference = 'Stop'
        $version = $(Get-Date -Format yyyyMMddHHmmss)
        docker build . --file Dockerfile --tag webapplication-aspnet:$version
        docker tag webapplication-aspnet:$version ${Env:DOCKER_USERNAME}/webapplication-aspnet:$version
        docker tag webapplication-aspnet:$version ${Env:DOCKER_USERNAME}/webapplication-aspnet:latest
        docker push ${Env:DOCKER_USERNAME}/webapplication-aspnet
